spring.application.name=horrorfilms

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/horrorfilms?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=horrorapp
spring.datasource.password=In906344##$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

tmdb.api.key=S32046f734e91472a10e1f87c890d3fa1
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.image-base-url=https://image.tmdb.org/t/p/w500
tmdb.genre.horror=27

app.cache.ttl-seconds=86400